apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
spec:
  tls:
    - secretName: example-tls
      hosts:
        - example.co.uk
  rules:
  - host: example.co.uk
    http:
      paths:
        - backend:
            serviceName: web
            servicePort: 80
