apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
spec:
  tls:
    - secretName: prism-challenge-tls
      hosts:
        - prism-challenge.co.uk
  rules:
  - host: prism-challenge.co.uk
    http:
      paths:
        - backend:
            serviceName: web
            servicePort: 80
