---

- hosts: local
  become: yes

  roles:
    - ../roles/install-sys-dependencies
    - ../roles/setup-user
    - ../roles/install-terraform
    - ../roles/install-kubectl
    - ../roles/install-helm
    - ../roles/install-aws-cli
    - ../roles/install-authenticator
    
    